"use client";

import { useState } from "react";
import Link from "next/link";
import RouteHeader, { RouteFooter } from "../components/RouteHeader";

export default function CheckoutPage() {
  const [paymentMethod, setPaymentMethod] = useState<"cod" | "online">("cod");
  return <main className="app"><RouteHeader active="shop" /><section className="simple-page checkout-page"><div className="page-title"><span className="kicker">Almost there</span><h1>Complete your order</h1><p>Review your delivery details and choose how you&apos;d like to pay.</p></div><div className="checkout-layout"><div className="checkout-form"><div className="checkout-section"><h2>Delivery details</h2><label>Full name<input defaultValue="Jamie Reyes" /></label><label>Delivery address<input defaultValue="24 Narra Street, New Manila, Quezon City" /></label><label>Delivery slot<select defaultValue="today"><option value="today">Today · 3:00–5:00 PM</option><option value="tomorrow">Tomorrow · 9:00–11:00 AM</option></select></label></div><div className="checkout-section"><h2>How would you like to pay?</h2><button type="button" className={`payment-choice ${paymentMethod === "cod" ? "selected" : ""}`} onClick={() => setPaymentMethod("cod")}><span>₱</span><div><strong>Cash on delivery</strong><small>Pay your rider when your order arrives</small></div>{paymentMethod === "cod" && <b>✓</b>}</button><button type="button" className={`payment-choice ${paymentMethod === "online" ? "selected" : ""}`} onClick={() => setPaymentMethod("online")}><span>▣</span><div><strong>Online payment</strong><small>Card, GCash, Maya, and online banking</small></div>{paymentMethod === "online" && <b>✓</b>}</button>{paymentMethod === "online" && <p className="payment-note">Online payment will be connected soon. You can select this option now while PayMongo setup is pending.</p>}</div></div><aside className="checkout-summary"><span className="kicker">Order summary</span><h2>3 items</h2><div><span>Market favorites</span><b>₱704</b></div><div><span>Delivery</span><b>₱59</b></div><div className="total"><span>Total</span><b>₱763</b></div><button className="primary checkout">Place order with {paymentMethod === "cod" ? "COD" : "online payment"} <span>→</span></button><small>{paymentMethod === "cod" ? "Pay safely when your order arrives." : "Payment integration will be enabled soon."}</small><Link href="/">← Continue shopping</Link></aside></div></section><RouteFooter /></main>;
}
